#!/usr/bin/env python3

if __name__ == '__main__':
    import os, sys
    arguments = sys.argv[1:]
    # file_name
    run_file_name = arguments[0]

    extra_args = ''
    if len(arguments) > 1:
        extra_args = f"{' '.join(arguments[1:])} "

    os.environ['PARALLEL_TYPE'] = 'ds'
    command = f'deepspeed {extra_args}{run_file_name}'

    print(f'run command {command}')
    os.system(command)
