#!/usr/bin/env python3

if __name__ == '__main__':
    import os, sys

    arguments = sys.argv[1:]
    # file name
    run_file_name = arguments[0]

    extra_args = ''
    if len(arguments) > 1:
        extra_args = f"{' '.join(arguments[1:])} "

    try:
        import deepspeed
        parallel_type = 'ds'
    except:
        parallel_type = 'none'

    os.environ['PARALLEL_TYPE'] = parallel_type

    if parallel_type == 'ds':
        command = f'deepspeed {extra_args}{run_file_name}'
    else:
        command = f'python3 {run_file_name}'

    print(f'run command {command}')
    os.system(command)
